#!/usr/bin/env bash
# redirecting to another page
apt-get update -y
apt-get install -y nginx
echo 'Holberton School' | tee /var/www/html/index.nginx-debian.html
sed -i 's/listen 80 default_server;/listen 80 default_server;\nrewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
service nginx restart