#!/usr/bin/env bash
# Displays "Holberton School" 10 times but for the 9th iteration display Hi
name="Holberton School"
counter=1

while [ $counter -le 10 ]
do
    echo "$name"
    if [ $counter -eq 9 ]
    then
	echo "Hi"
    fi
    ((counter++))
done
