#!/usr/bin/env bash
# Displays "Holberton School" 10 times but for the 9th iteration display Hi
name="Holberton School"
counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
	echo "bad luck"
    elif [ $counter -eq 8 ]
    then
	echo "good luck"
    else
	echo "$name"
    fi
    ((counter++))
done
