#!/usr/bin/env bash
# Displays number from 1 to 20 
count=1

while [ $count -le 20 ]
do
    echo $count
    if [ $count -eq 4 ]
    then
	echo "bad luck from China"
    elif [ $count -eq 9 ]
    then
	echo "bad luck from Japan"
    elif [ $count -eq 17 ]
    then
	echo "bad luck from Italy"
    fi
    ((count++))
    
done
