#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
hour=1
min=1

while [ $hour -le 12 ]
do
    echo "Hour: "$hour
    while [ $min -le 59 ]
    do
	echo $min
	((min++))
    done
    min=1
    ((hour++))
done
